blog/app/urls.py
from django.urls import path

from app import views


urlpatterns = [
    path('index/', views.Index.as_view(), name='index'),
    path('about/', views.About.as_view(), name='about'),
    path('menu/', views.Menu.as_view(), name='menu'),
    path('info/<int:id>/', views.Info.as_view(), name='info'),
    path('list/', views.List.as_view(), name='list'),
    path('search/', views.Search.as_view(), name='search'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 博客前台
    path('blog/', include(('app.urls', 'app'), namespace='blog')),
    # 管理后台
    path('backweb/', include(('backweb.urls', 'backweb'), namespace='backweb')),
    #  编辑器配置
    path(r'^ueditor/',include('DjangoUeditor.urls' )),
    # 首页
    path(r'', views.Index.as_view())

]

blog/templates/web/about.html
{% extends 'web/base_main.html' %}

{% block title %}
  王海飞个人博客 - 一个肥宅的个人博客网站
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
     {% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
    <script src="{% static 'web/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/hc-sticky.js' %}"></script>

    <script>


    </script>
{% endblock %}


{% block aboutme %}
<div class="about_me">
    <h2>关于我</h2>
    <ul>
        <i style="width:20%; height:20%;"><img src="/static/web/images/git_logo.png"></i>
        <p>
            <b>github地址:</b><br/>
            <a href="https://github.com/coco369/" target="_blank">https://github.com/coco369/</a>
        </p>
    </ul>
</div>
{% endblock %}


{% block main %}

  <main class="r_box">
      <input type="hidden" value="about" id="title_id">
     <div class="about">
      <p>王海飞，男，一个90后程序员！14年入行。先后经历过几家大型的公司，主要做Python后端研发工作。
          经历过O2O商城，大型ERP系统，全国最大的车辆网项目等<br/>
           <br />
            目前就职于一家教育机构，主要培训Python相关的课程。开发该个人博客网站主要是给学生参考，也是用于记录每天的学习笔记和心得等。
          好记性不如烂笔头，这句话，在教学的生涯中让我深刻的领会到其中的奥义。该博客网站每天都会有新的文章分享，尽情期待！<br />
            <br />
    近几年来忙于做开发工作，很多的技术也都是不够深入，甚至很多技术都是浅尝即止。由于开发任务比较繁重，个人笔记也都记录在CSDN、github、gitee上
          ，以至于都没有详细的整理出来，感觉省事惭愧。<br />
            <br />

          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.vincent-whf.com 创建于2017年01月12日&nbsp;</p>
          <br />
          <!--<p>备案号：蜀ICP备11002373号-1</p>-->
          <!--<br />-->
          <p>开发语言：Python3.7</p>
          <br />
          <p>框架：Django2.0.7</p>

     </div>
  </main>

{% endblock %}

blog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block extcss %}
    {% endblock %}

</head>
<body>
{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

{% block extjs %}
{% endblock %}

</body>
</html>

blog/templates/web/base_main.html
{% extends 'web/base.html' %}

{% block header %}
  <header class="header-navigation" id="header">
    <nav><div class="logo"><a href="/">王海飞个人博客</a></div>
      <h2 id="mnavh"><span class="navicon"></span></h2>
      <ul id="starlist">
        <li><a href="/">网站首页</a></li>
        <li><a href="{% url 'blog:list' %}">我的笔记</a></li>
        <li><a href="{% url 'blog:about' %}">关于我</a></li>
        <!--<li><a href="infopic.html">留言</a></li>-->
      </ul>
  </nav>
  </header>
{% endblock %}

{% block extjs %}
    {% load static %}
    <script src="{% static 'web/js/jquery.min.js' %}" type="text/javascript"></script>
    <script>

        $.get('/blog/menu/', function(data){
            for(var i=0; i<data.atypes.length;i++){
                types_li = '<li><a href="/blog/list/?type=' + data.atypes[i].types + '">' + data.atypes[i].types + '(' + data.atypes[i].article_count + ')</a></li>'
                $('.types_class').append(types_li)
            }
            for(var i=0; i<data.articles.length;i++){
                article_li = '<li><a href="/blog/info/' + data.articles[i].id + '/">' + data.articles[i].title + '</a></li>'
                $('.tuijian_class').append(article_li)
            }

        })
    </script>
{% endblock %}

{% block content %}
  <article>
    <aside class="l_box">
        {% block aboutme %}

        {% endblock %}
        <div class="search">
          <form action="/blog/search/" method="get">
            <input name="search_params" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
            <input class="input_submit" value="搜索" type="submit">
          </form>
        </div>
        <div class="fenlei">
            <h2>文章分类</h2>
            <ul class="types_class">
            </ul>
        </div>
        <div class="tuijian">
          <h2>站长推荐</h2>
          <ul class="tuijian_class">
          </ul>
        </div>
        <!--<div class="links">-->
            <!--<h2>友情链接</h2>-->
            <!--<ul>-->
                <!--<a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>-->
            <!--</ul>-->
        <!--</div>-->
        <div class="guanzhu">
            <h2>关注我的电影推荐公众号(开发中)</h2>
            <ul>
                {% load static %}
                <img src="{% static 'web/images/weixin_avatar.jpg' %}" style="width:60%; margin:0 auto;">
            </ul>
        </div>
    </aside>
      {% block main %}


      {% endblock %}
  </article>

{% endblock %}

{% block footer %}
  <footer>
    <p>Design by <a href="" target="_blank">王海飞个人博客</a> <a href="/">蜀ICP备</a></p>
  </footer>
  <a href="#" class="cd-top">Top</a>
{% endblock %}

blog/templates/web/index.html
{% extends 'web/base_main.html' %}

{% block title %}
  王海飞个人博客 - 一个肥宅的个人博客网站
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
  {% load static %}
    {{ block.super }}
  <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
  <script src="{% static 'web/js/modernizr.js' %}"></script>
{% endblock %}


{% block aboutme %}
<div class="about_me">
    <h2>关于我</h2>
    <ul>
        <i style="width:50%; height:50%;"><img src="/static/web/images/blog_avatar.png"></i>
        <p><b>王海飞</b>，一个90后典型的程序开发人员！14年入行。一直潜心研究Python技术，一边工作一边积累经验，分享一些开发中整理的笔记。</p>
    </ul>
</div>
{% endblock %}


{% block main %}
    <main class="r_box">
        {% for article in articles %}
            <li>
                <h3><a href="{% url 'blog:info' article.id %}">{{ article.title }}</a></h3>
                <p>{{ article.desc }}</p>
            </li>
        {% endfor %}
    </main>

{% endblock %}

blog/templates/web/info.html
{% extends 'web/base_main.html' %}

{% block title %}
  王海飞个人博客 - 一个肥宅的个人博客网站
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
  {% load static %}
    {{ block.super }}
  <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
  <script src="{% static 'web/js/modernizr.js' %}"></script>
{% endblock %}


{% block main %}

    <main>
        <div class="infosbox">
            <div class="newsview">
                <h3 class="news_title">{{ article.title }}</h3>
                <div class="bloginfo">
                    <ul>
                        <li class="author">作者：<a href="/">王海飞</a></li>
                        <li class="timer">时间：{{ article.create_time }}</li>
                        <!--<li class="view">4567人已阅读</li>-->
                    </ul>
                </div>
                <div class="tags">
                    <a href="/" target="_blank">个人博客</a> &nbsp;
                    <a href="/" target="_blank">{{ article.types.types }}</a>
                </div>
                <div class="news_about">
                   {{ article.content|safe }}
                </div>

            </div>
            <div class="share">
                <p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>13</b>)</p>
            </div>
            <div class="nextinfo">
                {% if last %}
                    <p>上一篇：
                        <a href="{% url 'blog:info' last.id %}">
                            {{ last.title }}
                        </a>
                    </p>
                {% endif %}
                {% if next %}
                    <p>下一篇：
                        <a href="{% url 'blog:info' next.id %}">
                            {{ next.title }}
                        </a>
                    </p>
                {% endif %}
            </div>
      <!--<div class="news_pl">-->
        <!--<h2>文章评论</h2>-->
        <!--<div class="gbko">-->
          <!--<script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>-->
          <!--<div class="fb">-->
            <!--<ul>-->
              <!--<p class="fbtime"><span>2018-07-24 11:52:38</span>dancesmile</p>-->
              <!--<p class="fbinfo">这才是我要的朋友圈</p>-->
            <!--</ul>-->
          <!--</div>-->
          <!--<div class="fb">-->
            <!--<ul>-->
              <!--<p class="fbtime"><span>2018-07-24 08:52:48</span> 卜野</p>-->
              <!--<p class="fbinfo"></p>-->
              <!--<div class="ecomment"><span class="ecommentauthor">网友 家蚂蚁 的原文：</span>-->
                <!--<p class="ecommenttext">坚持哟!看你每天都有写，请继续加油，再接再厉哦</p>-->
              <!--</div>-->
            <!--</ul>-->
          <!--</div>-->

          <!--<script>-->
		  <!--function CheckPl(obj)-->
		  <!--{-->
		  <!--if(obj.saytext.value=="")-->
		  <!--{-->
		  <!--alert("您没什么话要说吗？");-->
		  <!--obj.saytext.focus();-->
		  <!--return false;-->
		  <!--}-->
		  <!--return true;-->
		  <!--}-->
		  <!--</script>-->
          <!--<form action="/e/pl/doaction.php" method="post" name="saypl" id="saypl" onsubmit="return CheckPl(document.saypl)">-->
            <!--<div id="plpost">-->
              <!--<p class="saying"><span><a href="/e/pl/?classid=77&amp;id=106">共有<script type="text/javascript" src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>2条评论</a></span>来说两句吧...</p>-->
              <!--<p class="yname"><span>用户名:</span>-->
                <!--<input name="username" type="text" class="inputText" id="username" value="" size="16">-->
              <!--</p>-->
              <!--<p class="yzm"><span>验证码:</span>-->
                <!--<input name="key" type="text" class="inputText" size="16">-->
              <!--</p>-->
              <!--<input name="nomember" type="hidden" id="nomember" value="1" checked="checked">-->
              <!--<textarea name="saytext" rows="6" id="saytext"></textarea>-->
              <!--<input name="imageField" type="submit" value="提交">-->
              <!--<input name="id" type="hidden" id="id" value="106">-->
              <!--<input name="classid" type="hidden" id="classid" value="77">-->
              <!--<input name="enews" type="hidden" id="enews" value="AddPl">-->
              <!--<input name="repid" type="hidden" id="repid" value="0">-->
              <!--<input type="hidden" name="ecmsfrom" value="/joke/talk/2018-07-23/106.html">-->
            <!--</div>-->
          <!--</form>-->
        <!--</div>-->
      <!--</div>-->
        </div>
    </main>

{% endblock %}

blog/templates/web/search.html
{% extends 'web/base_main.html' %}

{% block title %}
  王海飞个人博客 - 一个肥宅的个人博客网站
{% endblock %}

{% block extcss %}
  {% load static %}
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/index.css' %}" rel="stylesheet">
  <link href="{% static 'web/css/m.css' %}" rel="stylesheet">
{% endblock %}

{% block extjs %}
     {% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'web/js/comm.js' %}"></script>
    <script src="{% static 'web/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/hc-sticky.js' %}"></script>
{% endblock %}


{% block main %}

    <main class="r_box">
        {% for article in articles %}
            <li>
                <h3><a href="{% url 'blog:info' article.id %}">{{ article.title }}</a></h3>
                <p>{{ article.desc }}</p>
            </li>
        {% endfor %}
        {% if articles %}
            <div class="pagelist">
                <a class="allpage"><b>共{{ articles.paginator.num_pages }}条</b></a>&nbsp;&nbsp;

                {% if articles.has_previous %}
                    <a href="{% url 'blog:list' %}?page={{ articles.previous_page_number }}&search_params={{ search_params }}">上一页</a>
                {% endif %}

                {% for i in articles.paginator.page_range %}
                    {% if articles.number == i %}
                        <a href="{% url 'blog:list' %}?page={{ i }}&search_params={{ search_params }}"  class="curPage">{{ i }}</a>&nbsp;&nbsp;
                    {% else%}
                        <a href="{% url 'blog:list' %}?page={{ i }}&search_params={{ search_params }}">{{ i }}</a>&nbsp;&nbsp;
                    {% endif %}

                {% endfor %}

                {% if articles.has_next %}
                    <a href="{% url 'blog:list' %}?page={{ articles.next_page_number }}&search_params={{ search_params }}">下一页</a>
                {% endif %}
            </div>
        {% else %}
            <p>还没发布文章呢</p>
        {% endif %}
    </main>

{% endblock %}