blog/app/urls.py
from django.urls import path

from app import views


urlpatterns = [
    path('index/', views.Index.as_view(), name='index'),
    path('about/', views.About.as_view(), name='about'),
    path('menu/', views.Menu.as_view(), name='menu'),
    path('info/<int:id>/', views.Info.as_view(), name='info'),
    path('list/', views.List.as_view(), name='list'),
    path('search/', views.Search.as_view(), name='search'),
]

blog/backweb/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from backweb import views


urlpatterns = [
    # 登录
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('index/', login_required(views.Index.as_view()), name='index'),
    path('add_article/', login_required(views.AddArticle.as_view()), name='add_article'),
    path('get_ctypes/', login_required(views.GetCtypes.as_view()), name='get_ctypes'),
    path('del_article/<int:id>/', login_required(views.DelArticle.as_view()), name='del_article'),
    path('edit_article/<int:id>/', login_required(views.EditArticle.as_view()), name='edit_article'),
    path('change_pwd/', login_required(views.ChangePwd.as_view()), name='change_pwd'),
    path('change_art_show/<int:id>/', login_required(views.ChangeArtShow.as_view()), name='change_art_show'),
    path('change_art_recommend/<int:id>/', login_required(views.ChangeArtRecommend.as_view()), name='change_art_recommend'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 博客前台
    path('blog/', include(('app.urls', 'app'), namespace='blog')),
    # 管理后台
    path('backweb/', include(('backweb.urls', 'backweb'), namespace='backweb')),
    #  编辑器配置
    path(r'^ueditor/',include('DjangoUeditor.urls' )),
    # 首页
    path(r'', views.Index.as_view())

]

blog/backweb/models.py
from django.db import models

from DjangoUeditor.models import UEditorField


class AType(models.Model):
    types = models.CharField(max_length=10)  # 类型
    f_typeid = models.IntegerField(null=True)  # 父id

    class Meta:
        db_table = 'article_type'

    def to_dict(self):
        return {
            'id': self.id,
            'types': self.types,
            'article_count': self.article_set.count(),
            'f_typeid': self.f_typeid,
        }


class Article(models.Model):
    title = models.CharField(max_length=30, null=False)  # 文章标题
    types = models.ForeignKey(AType, null=False, on_delete=models.CASCADE)  # 文章分类
    is_show = models.BooleanField(default=False) # 是否展示，False为不展示，True为展示
    is_recommend = models.BooleanField(default=False) # 是否推荐，False为不推荐，True为推荐
    desc = models.CharField(max_length=100, null=True)  # 内容描述
    content = UEditorField()  # 文章内容
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'article'

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'types': self.types.types,
            'desc': self.desc,
            'is_show': self.is_show,
            'content': self.content,
            'create_time': self.create_time.strftime('%Y-%m-%d')
        }

blog/backweb/forms.py
from django import forms
from django.contrib.auth.models import User

from backweb.models import Article, AType


class UserLoginForm(forms.Form):
    username = forms.CharField(required=True, error_messages={'required': '用户名必填'})
    password = forms.CharField(required=True, error_messages={'required': '密码必填'})

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username)
        if not user:
            raise forms.ValidationError('用户名不存在')
        else:
            return username


class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=30, required=True, error_messages={'required': '文章标题必填'})
    types = forms.IntegerField(required=True, error_messages={'required': '文章语言类型必填'})
    desc = forms.CharField(max_length=100, required=True, error_messages={'required': '文章副标题必填'})
    content = forms.Textarea()

    class Meta:
        model = Article
        fields = '__all__'

    def clean_types(self):
        """
        通过表单保存数据的时候，会提示types字段必须是AType的对象，但是页面中传递的types是id，而不是对象
        所以通过clean_types方法来返回AType的对象
        :return: AType的对象
        """
        types_id = self.cleaned_data['types']
        types = AType.objects.filter(id=types_id).first()
        return types


class UserChangePwdForm(forms.Form):

    passwd1 = forms.CharField(required=True)
    passwd2 = forms.CharField(required=True)

    def clean(self):
        passwd1 = self.cleaned_data.get('passwd1')
        passwd2 = self.cleaned_data.get('passwd2')
        if not passwd1:
            raise forms.ValidationError('密码必填')
        if not passwd2:
            raise forms.ValidationError('确认密码必填')
        if passwd2 != passwd1:
            raise forms.ValidationError({'passwd2': '两次密码不一致'})
        return passwd1

blog/backweb/views.py
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic.base import View

from backweb.forms import UserLoginForm, ArticleForm, UserChangePwdForm
from backweb.models import Article, AType
from blog.settings import ARTICLE_NUMBER


class Login(View):
    """
    登录页面，使用django提供的User表进行登录和权限校验
    """
    def get(self, request, *args, **kwargs):
        return render(request, 'backweb/login.html')

    def post(self, request, *args, **kwargs):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = auth.authenticate(request,
                                     username=form.cleaned_data.get('username'),
                                     password=form.cleaned_data.get('password')
                                     )
            if user:
                auth.login(request, user)
                return redirect('backweb:index')
            else:
                data = {'password': '账号密码错误'}
                return render(request, 'backweb/login.html', {'error': data})
        else:
            return render(request, 'backweb/login.html', {'error': form.errors})


class Logout(View):
    """
    注销账户
    """
    def get(self, request, *args, **kwargs):
        auth.logout(request)
        return redirect('backweb:login')


class Index(View):
    """
    管理后台首页地址
    """
    def get(self, request, *args, **kwargs):
        # 语言分类id

        ctype_id = request.GET.get('select_lang')
        art_is_show = request.GET.get('art_is_show')
        art_is_recommend = request.GET.get('art_is_recommend')
        select_lang_name = ''
        try:
            page = request.GET.get('page', 1)
        except Exception as e:
            page = 1
        atypes = AType.objects.filter(f_typeid=None)
        articles = Article.objects.all().order_by('-id')

        # 过滤文章分类
        if ctype_id:
            # django2.0版本中外键的查询，查询字段=对象，或则查询字段__id=id，或则查询字段=id
            articles = articles.filter(types=ctype_id)
            # 当前选择分类名
            select_lang_name = AType.objects.filter(id=ctype_id).first().types
        # 过滤是否展示
        if art_is_show:
            articles = articles.filter(is_show=art_is_show)
        # 过滤是否推荐
        if art_is_recommend:
            articles = articles.filter(is_recommend=art_is_recommend)

        paginator = Paginator(articles, ARTICLE_NUMBER)
        articles = paginator.page(page)
        return render(request, 'backweb/index.html', {'atypes': atypes,
                                                      'page': page,
                                                      'articles': articles,
                                                      'select_lang_name': select_lang_name,
                                                      'is_show': art_is_show,
                                                      'is_recommend': art_is_recommend})


class AddArticle(View):
    """
    发布文章
    """
    def get(self, request, *args, **kwargs):
        atypes = AType.objects.filter(f_typeid=None)
        return render(request, 'backweb/article_detail.html', {'atypes': atypes})

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST)
        # 校验form表单中的参数，使用is_valid()方法校验，验证成功则返回True，否则为False
        if form.is_valid():
            # 使用form表单保存数据
            form.save()
            # 保存成功后，跳转到首页
            return redirect('backweb:index')
        # 如果表单验证失败，则返回错误信息
        # return redirect('backweb:add_article')
        atypes = AType.objects.filter(f_typeid=None)
        return render(request, 'backweb/article_detail.html', {'error': form.errors, 'atypes': atypes})


class GetCtypes(View):
    """
    获取文章分类下具体的子分类
    """
    def get(self, request, *args, **kwargs):
        f_id = request.GET.get('f_id')
        c_types = AType.objects.filter(f_typeid=f_id)
        c_types = [c.to_dict() for c in c_types]
        return JsonResponse({'c_types': c_types})


class DelArticle(View):
    """
    删除文章
    """
    def post(self, request, *args, **kwargs):
        a_id = kwargs['id']
        Article.objects.filter(id=a_id).delete()
        return JsonResponse(data={'code':200})


class EditArticle(View):
    """
    编辑文章
    """

    def get(self, request, *args, **kwargs):
        aid = kwargs['id']
        article = Article.objects.get(id=aid)
        atypes = AType.objects.filter(f_typeid=None)
        return render(request, 'backweb/article_detail.html', {'article': article, 'atypes': atypes})

    def post(self, request, *args, **kwargs):
        aid = kwargs['id']
        article = Article.objects.get(id=aid)

        form = ArticleForm(request.POST, instance=article)
        # 校验form表单中的参数，使用is_valid()方法校验，验证成功则返回True，否则为False
        if form.is_valid():
            # 使用form表单保存数据
            form.save()
            # 保存成功后，跳转到首页
            return redirect('backweb:index')
        else:
            article = Article.objects.get(id=aid)
            atypes = AType.objects.filter(f_typeid=None)
            return render(request, 'backweb/article_detail.html', {'article': article,
                                                                   'error': form.errors,
                                                                   'atypes': atypes})


class ChangePwd(View):
    """
    修改密码
    """
    def get(self, request, *args, **kwargs):
        return render(request, 'backweb/change_pwd.html')

    def post(self, request, *args, **kwargs):
        form = UserChangePwdForm(request.POST)
        if form.is_valid():
            # 修改用户密码
            user = request.user
            user.set_password(request.POST.get('passwd2'))
            user.save()

        return render(request, 'backweb/change_pwd.html', {'error': form.errors})


class ChangeArtShow(View):
    """
    修改文章的展示状态
    """
    def get(self, request, *args, **kwargs):
        id = kwargs['id']
        article = Article.objects.filter(id=id).first()
        if article:
            if article.is_show:
                article.is_show = False
            else:
                article.is_show = True
            article.save()
        # return redirect('backweb:index')
        return redirect('/backweb/index/?art_is_show=0')


class ChangeArtRecommend(View):
    """
    修改文章的推荐状态
    """
    def get(self, request, *args, **kwargs):
        id = kwargs['id']
        article = Article.objects.filter(id=id).first()
        if article:
            if article.is_recommend:
                article.is_recommend = False
            else:
                article.is_recommend = True
            article.save()
        # return redirect('backweb:index')
        return redirect('/backweb/index/?art_is_show=0')

blog/templates/backweb/article_detail.html
{% extends 'backweb/base_main.html' %}
{% block title %}
 后台管理系统
{% endblock %}


{% block extcss %}
 {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'backweb/css/style.css' %}">
{% endblock %}

{% block extjs %}
 {% load static %}
 <script src="{% static 'backweb/js/html5.js' %}"></script>
 <script src="{% static 'backweb/js/jquery.js' %}"></script>
 <script src="{% static 'backweb/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
 <script>

     (function($){
         $(window).load(function(){

             $("a[rel='load-content']").click(function(e){
                 e.preventDefault();
                 var url=$(this).attr("href");
                 $.get(url,function(data){
                     $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
                     //scroll-to appended content
                     $(".content").mCustomScrollbar("scrollTo","h2:last");
                 });
             });

             $(".content").delegate("a[href='top']","click",function(e){
                 e.preventDefault();
                 $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
             });

         });
     })(jQuery);
 </script>

<script>
    function get_ctype(){
        var atype_id = $('#atype').val()
        $.get('/backweb/get_ctypes/?f_id=' + atype_id, function(data){
            ctype_options = ''
            for(var i=0; i<data.c_types.length; i++){
                ctype_option = '<option value="' + data.c_types[i].id + '">' + data.c_types[i].types + '</option>'
                ctype_options += ctype_option
            }
            $('#select_lang').html(ctype_options)
        })
    }

</script>

{% endblock %}

{% block content %}

{% include 'backweb/menu.html' %}

<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">

        <div class="page_title">
            <h2 class="fl">添加文章</h2>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章名称：</span>
                        <input type="text" class="textbox textbox_295" name="title" placeholder="文章名称..." value="{{ article.title }}"/>
                        <span class="errorTips">{{ error.title|striptags }}</span>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">内容描述：</span>
                        <input type="text" class="textbox textbox_295" name="desc" placeholder="描述..." value="{{ article.desc }}"/>
                        <span class="errorTips">{{ error.desc|striptags }}</span>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">前后端分类：</span>
                        <select class="select" id="atype" onchange="get_ctype();">
                            {% for atype in atypes %}
                                <option value="{{ atype.id }}" {% ifequal article.types.f_typeid atype.id %} selected {% endifequal %}>{{ atype.types }}</option>
                            {% endfor %}
                        </select>
                        <span class="errorTips"></span>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">语言分类：</span>
                        <select class="select" name="types" id="select_lang">
                            <option>选择分类</option>
                        </select>
                        <span class="errorTips">{{ error.types|striptags }}</span>
                    </li>
                    <script>
                        var atype_id = $('#atype option:selected').val()
                        $.get('/backweb/get_ctypes/?f_id=' + atype_id, function(data){
                            ctype_options = ''
                            for(var i=0; i<data.c_types.length; i++){
                                ctype_option = '<option value="' + data.c_types[i].id + '">' + data.c_types[i].types + '</option>'
                                ctype_options += ctype_option
                            }
                            $('#select_lang').html(ctype_options)
                        })
                    </script>
                    <li>
                        <span class="item_name" style="width:120px;">文章内容：</span>
                        <script id="editor" name="content" type="text/plain" style="width:800px;height:500px;margin-left:120px;margin-top:0;">
                            {{ article.content|safe }}
                        </script>
                        <script src="{% static 'backweb/js/ueditor.config.js' %}"></script>
                        <script src="{% static 'backweb/js/ueditor.all.min.js' %}"> </script>
                        <script type="text/javascript">

                            //实例化编辑器
                            //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例
                            var ue = UE.getEditor('editor');


                            function isFocus(e){
                                alert(UE.getEditor('editor').isFocus());
                                UE.dom.domUtils.preventDefault(e)
                            }
                            function setblur(e){
                                UE.getEditor('editor').blur();
                                UE.dom.domUtils.preventDefault(e)
                            }
                            function insertHtml() {
                                var value = prompt('插入html代码', '');
                                UE.getEditor('editor').execCommand('insertHtml', value)
                            }
                            function createEditor() {
                                enableBtn();
                                UE.getEditor('editor');
                            }
                            function getAllHtml() {
                                alert(UE.getEditor('editor').getAllHtml())
                            }
                            function getContent() {
                                var arr = [];
                                arr.push("使用editor.getContent()方法可以获得编辑器的内容");
                                arr.push("内容为：");
                                arr.push(UE.getEditor('editor').getContent());
                                alert(arr.join("\n"));
                            }
                            function getPlainTxt() {
                                var arr = [];
                                arr.push("使用editor.getPlainTxt()方法可以获得编辑器的带格式的纯文本内容");
                                arr.push("内容为：");
                                arr.push(UE.getEditor('editor').getPlainTxt());
                                alert(arr.join('\n'))
                            }
                            function setContent(isAppendTo) {
                                var arr = [];
                                arr.push("使用editor.setContent('欢迎使用ueditor')方法可以设置编辑器的内容");
                                UE.getEditor('editor').setContent('欢迎使用ueditor', isAppendTo);
                                alert(arr.join("\n"));
                            }
                            function setDisabled() {
                                UE.getEditor('editor').setDisabled('fullscreen');
                                disableBtn("enable");
                            }

                            function setEnabled() {
                                UE.getEditor('editor').setEnabled();
                                enableBtn();
                            }

                            function getText() {
                                //当你点击按钮时编辑区域已经失去了焦点，如果直接用getText将不会得到内容，所以要在选回来，然后取得内容
                                var range = UE.getEditor('editor').selection.getRange();
                                range.select();
                                var txt = UE.getEditor('editor').selection.getText();
                                alert(txt)
                            }

                            function getContentTxt() {
                                var arr = [];
                                arr.push("使用editor.getContentTxt()方法可以获得编辑器的纯文本内容");
                                arr.push("编辑器的纯文本内容为：");
                                arr.push(UE.getEditor('editor').getContentTxt());
                                alert(arr.join("\n"));
                            }
                            function hasContent() {
                                var arr = [];
                                arr.push("使用editor.hasContents()方法判断编辑器里是否有内容");
                                arr.push("判断结果为：");
                                arr.push(UE.getEditor('editor').hasContents());
                                alert(arr.join("\n"));
                            }
                            function setFocus() {
                                UE.getEditor('editor').focus();
                            }
                            function deleteEditor() {
                                disableBtn();
                                UE.getEditor('editor').destroy();
                            }
                            function disableBtn(str) {
                                var div = document.getElementById('btns');
                                var btns = UE.dom.domUtils.getElementsByTagName(div, "button");
                                for (var i = 0, btn; btn = btns[i++];) {
                                    if (btn.id == str) {
                                        UE.dom.domUtils.removeAttributes(btn, ["disabled"]);
                                    } else {
                                        btn.setAttribute("disabled", "true");
                                    }
                                }
                            }
                            function enableBtn() {
                                var div = document.getElementById('btns');
                                var btns = UE.dom.domUtils.getElementsByTagName(div, "button");
                                for (var i = 0, btn; btn = btns[i++];) {
                                    UE.dom.domUtils.removeAttributes(btn, ["disabled"]);
                                }
                            }

                            function getLocalData () {
                                alert(UE.getEditor('editor').execCommand( "getlocaldata" ));
                            }

                            function clearLocalData () {
                                UE.getEditor('editor').execCommand( "clearlocaldata" );
                                alert("已清空草稿箱")
                            }
                        </script>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                   </li>
                </ul>
            </section>
        </form>
    </div>
</section>

{% endblock %}

blog/templates/backweb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block extcss %}
    {% endblock %}

    {% block extjs %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

blog/templates/backweb/base_main.html
{% extends 'backweb/base.html' %}

{% block header %}
    <header>
        <h1><img src="/static/backweb/images/admin_logo.png"/></h1>
        <ul class="rt_nav">
            <li><a href="{% url 'blog:index' %}" target="_blank" class="website_icon">站点首页</a></li>
            <li><a href="{% url 'backweb:change_pwd' %}" class="set_icon">账号设置</a></li>
            <li><a href="{% url 'backweb:logout' %}" class="quit_icon">安全退出</a></li>
        </ul>
    </header>
{% endblock %}

blog/templates/backweb/index.html
{% extends 'backweb/base_main.html' %}
{% block title %}
 后台管理系统
{% endblock %}


{% block extcss %}
 {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'backweb/css/style.css' %}">
{% endblock %}

{% block extjs %}
 {% load static %}
 <script src="{% static 'backweb/js/html5.js' %}"></script>
 <script src="{% static 'backweb/js/jquery.js' %}"></script>
 <script src="{% static 'backweb/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
 <script>

    function get_ctype(){
        var atype_id = $('#atype').val()
        $.get('/backweb/get_ctypes/?f_id=' + atype_id, function(data){
            ctype_options = '<option value="">请选择分类</option>'
            for(var i=0; i<data.c_types.length; i++){
                ctype_option = '<option id="lang_' + data.c_types[i].id + '" value="' + data.c_types[i].id + '">' + data.c_types[i].types + '</option>'
                ctype_options += ctype_option
            }
            $('#select_lang').html(ctype_options)
        })
    }

    $.get('/backweb/get_ctypes/?f_id=' + {{ atypes.0.id }}, function(data){
        ctype_options = '<option value="">请选择分类</option>'
        for(var i=0; i<data.c_types.length; i++){
            ctype_option = '<option id="lang_' + data.c_types[i].id + '" value="' + data.c_types[i].id + '">' + data.c_types[i].types + '</option>'
            ctype_options += ctype_option
        }
        $('#select_lang').html(ctype_options)
    })

    function article_delete(aid){
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        $.ajax({
            url: '/backweb/del_article/' + aid + '/',
            dataType:'json',
            type:'POST',
            headers:{'X-CSRFToken': csrf},
            success:function(data){
                if(data.code == '200'){
                    location.href='/backweb/index/'
                }
            },
            error: function(data){
                alert('删除成功')
            }
        })
    }

    function change_search(){
        var atype_id = $('#select_lang option:selected').val()
        $('.search_types').attr('href', '/backweb/index/?ctype_id=' + atype_id)
    }

    <!--实现点击分页跳转地址-->
    function search_page(page_number){
        if(location.search.split('&page')[0]){
            page_prefix = location.href.split('&page=')[0]
            url = page_prefix + '&page=' + page_number
            location.href = url
        }
    }


 </script>
{% endblock %}

{% block content %}

{% include 'backweb/menu.html' %}

<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
            笔记列表页
        </h1>

        <div class="page_title">
            <h2 class="fl">
                文章列表
                {% if select_lang_name %}
                ----> 当前分类：{{ select_lang_name }}
                {% endif %}
            </h2>
            <a href="{% url 'backweb:add_article' %}" class="fr top_rt_btn add_icon">添加文章</a>
        </div>
        <form action="" method="get">
            <section class="mtb">
                {% if is_show %}
                <input type="hidden" name="art_is_show" value="{{ is_show }}">
                {% endif %}
                {% if is_recommend %}
                <input type="hidden" name="art_is_recommend" value="{{ is_recommend }}">
                {% endif %}
                <select class="select" id="atype" onchange="get_ctype();">
                    {% for atype in atypes %}
                        <option value="{{ atype.id }}">{{ atype.types }}</option>
                    {% endfor %}
                </select>
                <select class="select" id="select_lang" name="select_lang">
                </select>
                {% if page %}
                <input type="hidden" name="page" value="{{ page }}">
                {% endif %}
                <a href="" class="search_types">
                    <input type="submit" value="查询" class="group_btn"/>
                </a>
            </section>
        </form>
        <table class="table">
            <tr>
                <th>编号ID</th>
                <th>文章名称</th>
                <th>文章描述</th>
                <th>类型</th>
                <th>是否展示</th>
                <th>是否推荐</th>
                <th>创建时间</th>
                <th>展示/不展示操作</th>
                <th>是否推荐</th>
                <th>编辑操作</th>
            </tr>
            {% for article in articles %}
                <tr>
                    <td class="center">{{ article.id }}</td>
                    <td class="center">{{ article.title }}</td>
                    <td class="center">{{ article.desc }}</td>
                    <td class="center">{{ article.types.types }}</td>
                    <td class="center">{% if article.is_show %} 展示 {% else %} 不展示 {% endif %}</td>
                    <td class="center">{% if article.is_recommend %} 推荐 {% else %} 不推荐 {% endif %}</td>
                    <td class="center">{{ article.create_time }}</td>
                    {% csrf_token %}
                    <td class="center">
                        {% if article.is_show %}
                            <a href="{% url 'backweb:change_art_show' article.id %}">不展示</a>
                        {% else %}
                            <a href="{% url 'backweb:change_art_show' article.id %}">展示</a>
                        {% endif %}
                    </td>
                    <td class="center">
                        {% if article.is_recommend %}
                            <a href="{% url 'backweb:change_art_recommend' article.id %}">不推荐</a>
                        {% else %}
                            <a href="{% url 'backweb:change_art_recommend' article.id %}">推荐</a>
                        {% endif %}
                    </td>
                    <td class="center">
                        <a href="{% url 'backweb:edit_article' article.id %}" title="编辑" class="link_icon">&#101;</a>
                        <a onclick="article_delete({{ article.id }});" title="删除" class="link_icon">&#100;</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <aside class="paging">
            <a>当前{{ articles.number }}页</a>
            <a href="javascript:;" onclick="search_page(1)">第一页</a>
            {% for i in articles.paginator.page_range %}
                <a href="javascript:;" onclick="search_page({{ i }})"> {{ i }} </a>
            {% endfor %}
            <a href="javascript:;" onclick="search_page({{ articles.paginator.num_pages }})">最后一页</a>
        </aside>
 </div>
</section>

{% endblock %}

blog/templates/backweb/menu.html
<aside class="lt_aside_nav content mCustomScrollbar">
    <h2><a href="{% url 'backweb:index' %}">首页</a></h2>
    <ul>
        <li>
            <dl>
                <dt>我的笔记</dt>
        <!--当前链接则添加class:active-->
                <dd><a href="{% url 'backweb:index' %}?art_is_show=0" {% if is_show == '0' %} class="active" {% endif %}>文章列表(不展示)</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>文章管理</dt>
        <!--当前链接则添加class:active-->
                <dd><a href="{% url 'backweb:index' %}?art_is_show=1" {% if is_show == '1' %} class="active" {% endif %}>文章展示</a></dd>
                <dd><a href="{% url 'backweb:index' %}?art_is_recommend=1" {% if is_recommend %} class="active" {% endif %}>文章推荐</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>用户管理</dt>
                <dd><a href="{% url 'backweb:change_pwd' %}">修改密码</a></dd>
            </dl>
        </li>
    </ul>
</aside>